name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - run: git config --global --add safe.directory '*'

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Flutter Version
        run: flutter --version

      - name: Upgrade Flutter packages
        run: flutter pub upgrade

      - name: Get Dependencies
        run: flutter pub get

      # 👇 خطوة توليد الأيقونات
      - name: Generate app icons
        run: flutter pub run flutter_launcher_icons

      # 👇 خطوة البناء مع تعطيل tree shake للأيقونات
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: naghom.apk
          path: build/app/outputs/flutter-apk/app-release.apk